using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Omnitech.DTO.BusinessCentral.Alexide
{
    public class ConfigItem
    {
        public string Airpool { get; set; }
        public double Altezza { get; set; }
        public double Altezza_Incasso { get; set; }
        public string AnnelloDistanziale { get; set; }
        public string AsseCopertura_Tipo { get; set; }
        public string BordoContenitivo_Ant { get; set; }
        public string BordoContenitivo_DX { get; set; }
        public string BordoContenitivo_Post { get; set; }
        public string BordoContenitivo_SX { get; set; }
        public string BordoIkon { get; set; }
        public string BordoLine { get; set; }
        public double Btop_x { get; set; }
        public double Btop_y { get; set; }
        public string Bussole_Top { get; set; }
        public string Categoria { get; set; }
        public double Catino_Lunghezza { get; set; }
        public double Catino_Profondita { get; set; }
        public string CodiceColore { get; set; }
        public string CodiceMateriale { get; set; }
        public string CodiceMateriale_S2 { get; set; }
        public string CodiceMateriale_S3 { get; set; }
        public string Colorato { get; set; }
        public string DisegnoDaAttenzionare { get; set; }
        public string Erogatore { get; set; }
        public string FamigliaProdotto { get; set; }
        public string Finitura_foro { get; set; }
        public string Foratura_Tipo { get; set; }
        public string ForoMix { get; set; }
        public double ForoMix_Dimensione { get; set; }
        public double ForoMix_Offset_X { get; set; }
        public double ForoMix_Qta { get; set; }
        public double ForoMix_X { get; set; }
        public double ForoMix_Y { get; set; }
        public double Foro_Diametro { get; set; }
        public double Foro_Lunghezza { get; set; }
        public double Foro_Profondita { get; set; }
        public double Foro_Raggio { get; set; }
        public double Foro_X { get; set; }
        public double Foro_Y { get; set; }
        public string FresataLed_Tipo { get; set; }
        public string FresataVetro_Anteriore { get; set; }
        public string FresataVetro_DX { get; set; }
        public double FresataVetro_H { get; set; }
        public double FresataVetro_Lunghezza_L { get; set; }
        public double FresataVetro_Lunghezza_P { get; set; }
        public double FresataVetro_P { get; set; }
        public string FresataVetro_Posteriore { get; set; }
        public string FresataVetro_SX { get; set; }
        public double FresataVetro_X { get; set; }
        public double FresataVetro_Y { get; set; }
        public string Giunzione_Anteriore { get; set; }
        public string Giunzione_DX { get; set; }
        public string Giunzione_Posteriore { get; set; }
        public string Giunzione_SX { get; set; }
        public string Installazione_Tipo { get; set; }
        public double InterasseVasca_X { get; set; }
        public double InterasseVasca_Y { get; set; }
        public double InterasseVasche { get; set; }
        public double Interasse_Forature { get; set; }
        public string KitCaricaBatterie_ON { get; set; }
        public string LastraPiuVasca { get; set; }
        public string Lav_Bordo_ANT { get; set; }
        public string Lav_Bordo_DX { get; set; }
        public string Lav_Bordo_POST { get; set; }
        public string Lav_Bordo_SX { get; set; }
        public double Legni_Lunghezza { get; set; }
        public string Legni_Posizione { get; set; }
        public double Legni_Qta { get; set; }
        public double Legno_dx { get; set; }
        public double Legno_p1 { get; set; }
        public double Legno_p2 { get; set; }
        public double Legno_p3 { get; set; }
        public double Legno_sx { get; set; }
        public double Lunghezza { get; set; }
        public string MasselliBasi { get; set; }
        public string MaterialeCover { get; set; }
        public string MoldSize { get; set; }
        public string Muretto { get; set; }
        public string Muretto_XFLY_ON { get; set; }
        public double NumeroVasche_Stampo1 { get; set; }
        public double NumeroVasche_Stampo2 { get; set; }
        public double NumeroVasche_Stampo3 { get; set; }
        public double Partenza_Catino { get; set; }
        public double PortaAsciugamanoSup_L { get; set; }
        public double PortaAsciugamanoSup_P { get; set; }
        public double PortaAsciugamanoSup_R { get; set; }
        public string PortaAsciugamanoSup_Tipo { get; set; }
        public double PortaAsciugamanoSup_X { get; set; }
        public double PortaAsciugamanoSup_Y { get; set; }
        public double PortaAsciugamanoVelettaDx_INT { get; set; }
        public double PortaAsciugamanoVelettaDx_L { get; set; }
        public double PortaAsciugamanoVelettaDx_P { get; set; }
        public double PortaAsciugamanoVelettaDx_R { get; set; }
        public string PortaAsciugamanoVelettaDx_Tipo { get; set; }
        public double PortaAsciugamanoVelettaDx_X { get; set; }
        public double PortaAsciugamanoVelettaDx_Y { get; set; }
        public double PortaAsciugamanoVelettaFrontale_INT { get; set; }
        public double PortaAsciugamanoVelettaFrontale_L { get; set; }
        public double PortaAsciugamanoVelettaFrontale_P { get; set; }
        public double PortaAsciugamanoVelettaFrontale_R { get; set; }
        public string PortaAsciugamanoVelettaFrontale_Tipo { get; set; }
        public double PortaAsciugamanoVelettaFrontale_X { get; set; }
        public double PortaAsciugamanoVelettaFrontale_Y { get; set; }
        public double PortaAsciugamanoVelettaSx_INT { get; set; }
        public double PortaAsciugamanoVelettaSx_L { get; set; }
        public double PortaAsciugamanoVelettaSx_P { get; set; }
        public double PortaAsciugamanoVelettaSx_R { get; set; }
        public string PortaAsciugamanoVelettaSx_Tipo { get; set; }
        public double PortaAsciugamanoVelettaSx_X { get; set; }
        public double PortaAsciugamanoVelettaSx_Y { get; set; }
        public string PostVerniciatura { get; set; }
        public string PostVerniciatura_CodiceColore { get; set; }
        public string PostVerniciatura_Tipo { get; set; }
        public double Profondita { get; set; }
        public double Raggio_Bordo1 { get; set; }
        public double Raggio_Bordo2 { get; set; }
        public double Raggio_Bordo3 { get; set; }
        public double Raggio_Bordo4 { get; set; }
        public string Raggio_Bordo_ON { get; set; }
        public string RicarcaWireless_ON { get; set; }
        public string RinforzoFronte { get; set; }
        public string RinforzoRetro { get; set; }
        public string Risega_Anteriore_DX { get; set; }
        public double Risega_Anteriore_DX_L { get; set; }
        public double Risega_Anteriore_DX_P { get; set; }
        public string Risega_Anteriore_SX { get; set; }
        public double Risega_Anteriore_SX_L { get; set; }
        public double Risega_Anteriore_SX_P { get; set; }
        public string Risega_Posteriore_DX { get; set; }
        public double Risega_Posteriore_DX_L { get; set; }
        public double Risega_Posteriore_DX_P { get; set; }
        public string Risega_Posteriore_SX { get; set; }
        public double Risega_Posteriore_SX_L { get; set; }
        public double Risega_Posteriore_SX_P { get; set; }
        public string Risega_Tipo { get; set; }
        public double RitaglioVascaOffset { get; set; }
        public double RitaglioVasca_L { get; set; }
        public double RitaglioVasca_P { get; set; }
        public string Rubinetteria_XFLY_Tipo { get; set; }
        public string Sagomatura_XFLY { get; set; }
        public string Salvagoccia { get; set; }
        public double ScaricoL { get; set; }
        public double ScaricoOffset_L { get; set; }
        public double ScaricoP { get; set; }
        public double ScaricoR { get; set; }
        public string SedeCoverQuadrata_Tipo { get; set; }
        public double Spessore { get; set; }
        public int Staffa_QT { get; set; }
        public string StampareDritto { get; set; }
        public string Stampo { get; set; }
        public string Stampo2 { get; set; }
        public string Stampo3 { get; set; }
        public string Taglio45_Anteriore { get; set; }
        public string Taglio45_DX { get; set; }
        public string Taglio45_Posteriore { get; set; }
        public string Taglio45_SX { get; set; }
        public string Telaio { get; set; }
        public string Texture_ON { get; set; }
        public string Texture_Tipo { get; set; }
        public string TipoFinitura { get; set; }
        public string TipologiaImballo { get; set; }
        public string TipologiaPiletta { get; set; }
        public string TipoVerniciatura { get; set; }
        public string Trattamento { get; set; }
        public string TroppoPieno_Tipo { get; set; }
        public string VanoGiorno_XFLY_ON { get; set; }
        public double Vasca_L { get; set; }
        public double Vasca_P { get; set; }
        public string Veletta_DX_ON { get; set; }
        public string Veletta_FRONTALE_ON { get; set; }
        public double Veletta_RETROCX_Lunghezza { get; set; }
        public string Veletta_RETRODX_ON { get; set; }
        public string Veletta_RETROSX_ON { get; set; }
        public string Veletta_RETRO_ON { get; set; }
        public double Veletta_RinforzoDX_Lunghezza { get; set; }
        public string Veletta_RinforzoDX_ON { get; set; }
        public double Veletta_RinforzoDX_X { get; set; }
        public double Veletta_RinforzoFRONTALE_Lunghezza { get; set; }
        public string Veletta_RinforzoFRONTALE_ON { get; set; }
        public double Veletta_RinforzoFRONTALE_Y { get; set; }
        public double Veletta_RinforzoSX_Lunghezza { get; set; }
        public string Veletta_RinforzoSX_ON { get; set; }
        public double Veletta_RinforzoSX_X { get; set; }
        public string Veletta_SX_ON { get; set; }
        public double Velette_Altezza { get; set; }
        public double Velette_Spessore { get; set; }
    }
}
